const statusText = document.getElementById("status");
const input = document.getElementById("userInput");
const sendBtn = document.getElementById("sendBtn");
const chat = document.getElementById("chat");

input.disabled = true;
sendBtn.disabled = true;

function addMessage(role, text) {
  const div = document.createElement("div");
  div.className = role;
  div.innerText = text;
  chat.appendChild(div);
  chat.scrollTop = chat.scrollHeight;
}

async function checkStatus() {
  const res = await fetch("/plugin/status");
  const data = await res.json();

  if (data.connected) {
    statusText.innerText = "Plugin connected";
    input.disabled = false;
    sendBtn.disabled = false;

    if (!data.permissionsGranted) {
      addMessage("assistant",
        "I can create scripts, parts, and systems in your Roblox game.\n\nDo you allow me to start creating automatically?"
      );
    }
  } else {
    statusText.innerText = "Plugin not connected";
    input.disabled = true;
    sendBtn.disabled = true;
  }
}

setInterval(checkStatus, 2000);
checkStatus();

sendBtn.onclick = async () => {
  const msg = input.value.trim();
  if (!msg) return;

  addMessage("user", msg);
  input.value = "";

  if (msg.toLowerCase() === "yes") {
    await fetch("/plugin/permissions", { method: "POST" });
    addMessage("assistant", "Permission granted. What do you want to create?");
    return;
  }

  // VERY BASIC AI PARSER (expand later)
  const instruction = {
    action: "create_script",
    parent: "ServerScriptService",
    name: "GeneratedScript",
    content: "-- generated by Hez AI\nprint('Hello world')"
  };

  await fetch("/ai/instruction", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(instruction)
  });

  addMessage("assistant", "Created Script in ServerScriptService");
};
